name: mapia
description: A beautiful REST API client for desktop.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3
  uuid: ^3.0.7
  path_provider: ^2.1.3
  window_manager: ^0.3.9
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  file_picker: ^8.0.7
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  split_view: ^3.2.1
  http_parser: ^4.0.2
  shared_preferences: ^2.2.3
  flutter_widget_from_html: ^0.17.1
  flutter_widget_from_html_core: ^0.17.0
  flutter_highlight: ^0.7.0
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.4
  flutter_distributor: ^0.5.1
  msix: ^3.16.7

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "mapia.png"
  windows:
    generate: true
    image_path: "mapia.png"
  macos:
    generate: true
    image_path: "mapia.png"
  linux:
    generate: true
    image_path: "mapia.png"

flutter:
  uses-material-design: true
  assets:
    - mapia.png

msix_config:
  display_name: Mapia
  publisher_display_name: Allensandiego
  publisher: CN=Allensandiego, O=Allensandiego, L=City, S=State, C=Country
  identity_name: com.allensandiego.mapia
  install_description: Mapia - REST API Client for Desktop.
  logo_path: mapia.png
  install_scope: user # Enable non-admin installation
