display_name: Mapia
package_name: mapia
version: 1.0.0+1
maintainer:
  name: Allen San Diego
  email: allensandiego@example.com
priority: optional
section: x11
installed_size: 250000
icon_path: mapia.png
