import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../providers/tabs_provider.dart';
import '../../providers/collection_provider.dart';
import '../../providers/environment_provider.dart';
import '../../../core/constants/http_constants.dart';
import '../../../core/theme/mapia_colors.dart';
import '../../../core/widgets/key_value_editor.dart';
import '../../../core/widgets/code_viewer.dart';
import '../../../core/utils/http_utils.dart';
import '../../../core/utils/variable_parser.dart';
import '../../../domain/entities/api_request.dart';
import '../../../data/services/http_service.dart';
import '../../../core/widgets/variable_text_editing_controller.dart';
import '../../../core/widgets/variable_autocomplete_field.dart';

class RequestEditor extends ConsumerStatefulWidget {
  final RequestTab tab;
  const RequestEditor({super.key, required this.tab});

  @override
  ConsumerState<RequestEditor> createState() => _RequestEditorState();
}

class _RequestEditorState extends ConsumerState<RequestEditor>
    with SingleTickerProviderStateMixin {
  late TabController _tabCtrl;

  @override
  void initState() {
    super.initState();
    _tabCtrl = TabController(length: 4, vsync: this);
  }

  @override
  void dispose() {
    _tabCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final req = widget.tab.request;
    final notifier = ref.read(tabsProvider.notifier);

    // Collect available environment variables
    final activeEnvVars = ref.watch(activeEnvVariablesProvider);
    final allVars = <String>{...activeEnvVars.keys};
    final resolvedVars = Map<String, String>.from(activeEnvVars);
    if (widget.tab.collectionId != null) {
      final collections = ref.watch(collectionsProvider).value ?? [];
      final col =
          collections.where((c) => c.id == widget.tab.collectionId).firstOrNull;
      if (col != null) {
        if (col.environmentId != null) {
          final envs = ref.watch(environmentsProvider).value ?? [];
          final linkedEnv =
              envs.where((e) => e.id == col.environmentId).firstOrNull;
          if (linkedEnv != null) {
            for (final v in linkedEnv.variables.where((v) => v.enabled)) {
              allVars.add(v.key);
              resolvedVars.putIfAbsent(v.key, () => v.value);
            }
          }
        }
        for (final v in col.variables.where((v) => v.enabled)) {
          allVars.add(v.key);
          resolvedVars.putIfAbsent(v.key, () => v.value);
        }
      }
    }
    for (final v in req.variables.where((v) => v.enabled)) {
      allVars.add(v.key);
      resolvedVars.putIfAbsent(v.key, () => v.value);
    }
    final envVarsList = allVars.toList();

    return Column(
      children: [
        // Sub-tab bar
        Container(
          color: context.colors.bgSurface,
          child: TabBar(
            controller: _tabCtrl,
            isScrollable: true,
            tabAlignment: TabAlignment.start,
            labelStyle:
                const TextStyle(fontSize: 12, fontWeight: FontWeight.w500),
            tabs: const [
              Tab(text: 'Authorization'),
              Tab(text: 'Headers'),
              Tab(text: 'Params'),
              Tab(text: 'Body'),
            ],
          ),
        ),
        const Divider(height: 1),
        // Tab content
        Expanded(
          child: TabBarView(
            controller: _tabCtrl,
            children: [
              // Auth
              _AuthEditor(tab: widget.tab),
              // Headers
              SingleChildScrollView(
                child: Column(
                  children: [
                    KeyValueEditor(
                      items: req.headers,
                      keyHint: 'Header',
                      valueHint: 'Value',
                      envVars: envVarsList,
                      resolvedEnvVars: resolvedVars,
                      onChanged: (v) => notifier.updateRequest(
                        widget.tab.id,
                        req.copyWith(headers: v),
                      ),
                    ),
                    _AutoGeneratedHeaders(request: req),
                  ],
                ),
              ),
              // Params
              SingleChildScrollView(
                child: KeyValueEditor(
                  items: req.queryParams,
                  keyHint: 'Key',
                  valueHint: 'Value',
                  envVars: envVarsList,
                  resolvedEnvVars: resolvedVars,
                  onChanged: (v) => notifier.updateRequest(
                    widget.tab.id,
                    req.copyWith(queryParams: v),
                  ),
                ),
              ),
              // Body
              _BodyEditor(tab: widget.tab),
            ],
          ),
        ),
      ],
    );
  }
}

// ─── Body Editor ────────────────────────────────────────────────────────────

class _BodyEditor extends ConsumerWidget {
  final RequestTab tab;
  const _BodyEditor({required this.tab});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final req = tab.request;
    final notifier = ref.read(tabsProvider.notifier);

    // Collect available environment variables
    final activeEnvVars = ref.watch(activeEnvVariablesProvider);
    final allVars = <String>{...activeEnvVars.keys};
    final resolvedVars = Map<String, String>.from(activeEnvVars);
    if (tab.collectionId != null) {
      final collections = ref.watch(collectionsProvider).value ?? [];
      final col =
          collections.where((c) => c.id == tab.collectionId).firstOrNull;
      if (col != null) {
        if (col.environmentId != null) {
          final envs = ref.watch(environmentsProvider).value ?? [];
          final linkedEnv =
              envs.where((e) => e.id == col.environmentId).firstOrNull;
          if (linkedEnv != null) {
            for (final v in linkedEnv.variables.where((v) => v.enabled)) {
              allVars.add(v.key);
              resolvedVars.putIfAbsent(v.key, () => v.value);
            }
          }
        }
        for (final v in col.variables.where((v) => v.enabled)) {
          allVars.add(v.key);
          resolvedVars.putIfAbsent(v.key, () => v.value);
        }
      }
    }
    for (final v in req.variables.where((v) => v.enabled)) {
      allVars.add(v.key);
      resolvedVars.putIfAbsent(v.key, () => v.value);
    }
    final envVarsList = allVars.toList();

    return Column(
      children: [
        // Editor area — the body-type dropdown is embedded inside each sub-editor's toolbar
        Expanded(
            child: _buildBodyContent(
                context, req, notifier, envVarsList, resolvedVars)),
      ],
    );
  }

  Widget _buildBodyContent(BuildContext context, ApiRequest request, notifier,
      List<String> envVarsList, Map<String, String> resolvedVars) {
    switch (request.bodyType) {
      case BodyType.none:
        return Column(
          children: [
            _BodyTypeBar(tab: tab),
            const Divider(height: 1),
            Expanded(
              child: Center(
                child: Text('No body for this request.',
                    style: TextStyle(
                        fontSize: 12, color: context.colors.textMuted)),
              ),
            ),
          ],
        );
      case BodyType.formData:
      case BodyType.urlEncoded:
        return Column(
          children: [
            _BodyTypeBar(tab: tab),
            const Divider(height: 1),
            Expanded(
              child: SingleChildScrollView(
                child: KeyValueEditor(
                  items: request.formDataFields,
                  keyHint: 'Key',
                  valueHint: 'Value',
                  envVars: envVarsList,
                  resolvedEnvVars: resolvedVars,
                  onChanged: (v) => notifier.updateRequest(
                    tab.id,
                    request.copyWith(formDataFields: v),
                  ),
                ),
              ),
            ),
          ],
        );
      case BodyType.json:
      case BodyType.raw:
      case BodyType.binary:
        return _RawBodyEditor(
          tab: tab,
          resolvedEnvVars: resolvedVars,
          envVars: envVarsList,
        );
    }
  }
}

// ─── Body Type Bar (Row of ChoiceChips) ──────────────────────────────────────

class _BodyTypeBar extends ConsumerWidget {
  final RequestTab tab;
  const _BodyTypeBar({required this.tab});

  String _label(BodyType t) {
    switch (t) {
      case BodyType.none:
        return 'none';
      case BodyType.json:
        return 'JSON';
      case BodyType.formData:
        return 'form-data';
      case BodyType.urlEncoded:
        return 'x-www-form-urlencoded';
      case BodyType.raw:
        return 'raw';
      case BodyType.binary:
        return 'binary';
    }
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final req = tab.request;
    final notifier = ref.read(tabsProvider.notifier);
    return Container(
      color: context.colors.bgSurface,
      padding: const EdgeInsets.all(8),
      child: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Row(
          children: BodyType.values.map((t) {
            return Padding(
              padding: const EdgeInsets.only(right: 8),
              child: ChoiceChip(
                label: Text(_label(t)),
                selected: req.bodyType == t,
                onSelected: (_) {
                  notifier.updateRequest(tab.id, req.copyWith(bodyType: t));
                },
              ),
            );
          }).toList(),
        ),
      ),
    );
  }
}

class _RawBodyEditor extends ConsumerStatefulWidget {
  final RequestTab tab;
  final Map<String, String>? resolvedEnvVars;
  final List<String>? envVars;
  const _RawBodyEditor({required this.tab, this.resolvedEnvVars, this.envVars});

  @override
  ConsumerState<_RawBodyEditor> createState() => _RawBodyEditorState();
}

class _RawBodyEditorState extends ConsumerState<_RawBodyEditor>
    with SingleTickerProviderStateMixin {
  late VariableTextEditingController _ctrl;
  late TabController _tabCtrl;
  final FocusNode _focus = FocusNode();

  @override
  void initState() {
    super.initState();
    _ctrl = VariableTextEditingController(text: widget.tab.request.body);
    _tabCtrl = TabController(length: 2, vsync: this);
  }

  @override
  void didUpdateWidget(_RawBodyEditor old) {
    super.didUpdateWidget(old);
    if (old.tab.id != widget.tab.id) {
      _ctrl.text = widget.tab.request.body;
    }
  }

  @override
  void dispose() {
    _ctrl.dispose();
    _tabCtrl.dispose();
    _focus.dispose();
    super.dispose();
  }

  String get _language {
    switch (widget.tab.request.bodyType) {
      case BodyType.json:
        return 'json';
      case BodyType.raw:
        return 'plaintext';
      default:
        return 'plaintext';
    }
  }

  String _bodyTypeLabel(BodyType t) {
    switch (t) {
      case BodyType.none:
        return 'none';
      case BodyType.json:
        return 'JSON';
      case BodyType.formData:
        return 'form-data';
      case BodyType.urlEncoded:
        return 'x-www-form-urlencoded';
      case BodyType.raw:
        return 'raw';
      case BodyType.binary:
        return 'binary';
    }
  }

  @override
  Widget build(BuildContext context) {
    final req = widget.tab.request;

    _ctrl.variableColor = context.colors.warning;
    _ctrl.defaultColor = context.colors.textPrimary;

    return Column(
      children: [
        // Combined: Edit/Preview tabs (left) + Body type dropdown (right)
        Container(
          height: 36,
          color: context.colors.bgSurface,
          child: Row(
            children: [
              // Edit / Preview tabs take up the remaining space
              Expanded(
                child: TabBar(
                  controller: _tabCtrl,
                  isScrollable: true,
                  tabAlignment: TabAlignment.start,
                  labelStyle: const TextStyle(
                      fontSize: 11, fontWeight: FontWeight.w500),
                  tabs: const [
                    Tab(text: 'Edit'),
                    Tab(text: 'Preview'),
                  ],
                ),
              ),
              // Body type dropdown — right-aligned
              Padding(
                padding: const EdgeInsets.only(right: 8),
                child: DropdownButtonHideUnderline(
                  child: DropdownButton<BodyType>(
                    value: req.bodyType,
                    isDense: true,
                    style: TextStyle(
                      fontSize: 12,
                      color: context.colors.textSecondary,
                    ),
                    dropdownColor: context.colors.bgElevated,
                    icon: Icon(Icons.arrow_drop_down,
                        size: 16, color: context.colors.textMuted),
                    items: BodyType.values.map((t) {
                      return DropdownMenuItem(
                        value: t,
                        child: Text(_bodyTypeLabel(t),
                            style: TextStyle(
                                fontSize: 12,
                                color: context.colors.textPrimary)),
                      );
                    }).toList(),
                    onChanged: (t) {
                      if (t != null) {
                        ref.read(tabsProvider.notifier).updateRequest(
                            widget.tab.id, req.copyWith(bodyType: t));
                      }
                    },
                  ),
                ),
              ),
            ],
          ),
        ),
        const Divider(height: 1),
        Expanded(
          child: TabBarView(
            controller: _tabCtrl,
            children: [
              Builder(
                builder: (context) {
                  final text = _ctrl.text;
                  final hasVars = text.contains('{{');
                  final resolvedText = (hasVars &&
                          widget.resolvedEnvVars != null)
                      ? VariableParser.resolve(text, widget.resolvedEnvVars!)
                      : null;

                  return Container(
                    color: context.colors.bgBase,
                    decoration: BoxDecoration(
                      color: context.colors.bgBase,
                      border: hasVars
                          ? Border.all(
                              color:
                                  context.colors.warning.withValues(alpha: 0.4),
                              width: 1.0,
                            )
                          : null,
                    ),
                    child: Builder(
                      builder: (context) {
                        Widget editField = VariableAutocompleteField(
                          controller: _ctrl,
                          focusNode: _focus,
                          maxLines: null,
                          expands: true,
                          envVars: widget.envVars ?? [],
                          resolvedEnvVars: widget.resolvedEnvVars,
                          onChanged: (v) {
                            ref.read(tabsProvider.notifier).updateRequest(
                                  widget.tab.id,
                                  widget.tab.request.copyWith(body: v),
                                );
                          },
                          style: TextStyle(
                            fontFamily: 'monospace',
                            fontSize: 13,
                            color: context.colors.textPrimary,
                            height: 1.6,
                          ),
                          decoration: InputDecoration(
                            border: InputBorder.none,
                            enabledBorder: InputBorder.none,
                            focusedBorder: InputBorder.none,
                            contentPadding: const EdgeInsets.all(12),
                            filled: true,
                            fillColor: context.colors.bgBase,
                            hintText: '{\n  "key": "value"\n}',
                          ),
                        );

                        if (resolvedText != null && resolvedText != text) {
                          editField = Tooltip(
                            message: resolvedText,
                            preferBelow: true,
                            decoration: BoxDecoration(
                              color: context.colors.bgElevated,
                              borderRadius: BorderRadius.circular(6),
                              border: Border.all(
                                  color: context.colors.warning
                                      .withValues(alpha: 0.4)),
                            ),
                            textStyle: TextStyle(
                              fontSize: 12,
                              color: context.colors.warning,
                              fontFamily: 'monospace',
                            ),
                            child: editField,
                          );
                        }

                        return editField;
                      },
                    ),
                  );
                },
              ),
              // ── Preview tab: read-only syntax-highlighted view ──────────
              Container(
                color: const Color(0xFF282C34), // atom-one-dark background
                child: Scrollbar(
                  child: SingleChildScrollView(
                    child: SelectionArea(
                      child: CodeViewer(
                        code: _ctrl.text,
                        language: _language,
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

// ─── Auth Editor ────────────────────────────────────────────────────────────

class _AuthEditor extends ConsumerWidget {
  final RequestTab tab;
  const _AuthEditor({required this.tab});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final req = tab.request;
    final auth = req.auth;
    final notifier = ref.read(tabsProvider.notifier);

    // Collect available environment variables
    final activeEnvVars = ref.watch(activeEnvVariablesProvider);
    final allVars = <String>{...activeEnvVars.keys};
    final resolvedVars = Map<String, String>.from(activeEnvVars);

    if (tab.collectionId != null) {
      final collections = ref.watch(collectionsProvider).value ?? [];
      final col =
          collections.where((c) => c.id == tab.collectionId).firstOrNull;
      if (col != null) {
        if (col.environmentId != null) {
          final envs = ref.watch(environmentsProvider).value ?? [];
          final linkedEnv =
              envs.where((e) => e.id == col.environmentId).firstOrNull;
          if (linkedEnv != null) {
            for (final v in linkedEnv.variables.where((v) => v.enabled)) {
              allVars.add(v.key);
              resolvedVars.putIfAbsent(v.key, () => v.value);
            }
          }
        }
        for (final v in col.variables.where((v) => v.enabled)) {
          allVars.add(v.key);
          resolvedVars.putIfAbsent(v.key, () => v.value);
        }
      }
    }
    for (final v in req.variables.where((v) => v.enabled)) {
      allVars.add(v.key);
      resolvedVars.putIfAbsent(v.key, () => v.value);
    }
    final envVarsList = allVars.toList();

    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Column 1: Auth Type Selector
          SizedBox(
            width: 250,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Type',
                    style: TextStyle(
                        color: context.colors.textPrimary,
                        fontWeight: FontWeight.bold,
                        fontSize: 14)),
                const SizedBox(height: 8),
                DropdownButtonFormField<AuthType>(
                  initialValue: auth.type,
                  dropdownColor: context.colors.bgElevated,
                  style: TextStyle(
                      color: context.colors.textPrimary, fontSize: 14),
                  decoration: const InputDecoration(
                    border: OutlineInputBorder(),
                  ),
                  items: AuthType.values.map((t) {
                    return DropdownMenuItem(
                      value: t,
                      child: Text(_authLabel(t)),
                    );
                  }).toList(),
                  onChanged: (t) => t != null
                      ? notifier.updateRequest(
                          tab.id, req.copyWith(auth: auth.copyWith(type: t)))
                      : null,
                ),
              ],
            ),
          ),
          const SizedBox(width: 48),
          // Column 2: Auth Fields
          Expanded(
            child: ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 400),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  if (auth.type == AuthType.bearer)
                    _AuthField(
                      label: 'Token',
                      value: auth.token,
                      hint: 'Bearer token',
                      envVars: envVarsList,
                      resolvedEnvVars: resolvedVars,
                      onChanged: (v) => notifier.updateRequest(
                          tab.id, req.copyWith(auth: auth.copyWith(token: v))),
                    ),
                  if (auth.type == AuthType.basic) ...[
                    _AuthField(
                      label: 'Username',
                      value: auth.username,
                      hint: 'Username',
                      envVars: envVarsList,
                      resolvedEnvVars: resolvedVars,
                      onChanged: (v) => notifier.updateRequest(tab.id,
                          req.copyWith(auth: auth.copyWith(username: v))),
                    ),
                    const SizedBox(height: 16),
                    _AuthField(
                      label: 'Password',
                      value: auth.password,
                      hint: 'Password',
                      obscure: true,
                      envVars: envVarsList,
                      resolvedEnvVars: resolvedVars,
                      onChanged: (v) => notifier.updateRequest(tab.id,
                          req.copyWith(auth: auth.copyWith(password: v))),
                    ),
                  ],
                  if (auth.type == AuthType.apiKey) ...[
                    _AuthField(
                      label: 'Header',
                      value: auth.apiKeyHeader,
                      hint: 'X-API-Key',
                      envVars: envVarsList,
                      resolvedEnvVars: resolvedVars,
                      onChanged: (v) => notifier.updateRequest(tab.id,
                          req.copyWith(auth: auth.copyWith(apiKeyHeader: v))),
                    ),
                    const SizedBox(height: 16),
                    _AuthField(
                      label: 'Value',
                      value: auth.apiKeyValue,
                      hint: 'Your API key',
                      obscure: true,
                      envVars: envVarsList,
                      resolvedEnvVars: resolvedVars,
                      onChanged: (v) => notifier.updateRequest(tab.id,
                          req.copyWith(auth: auth.copyWith(apiKeyValue: v))),
                    ),
                  ],
                  if (auth.type == AuthType.oauth2)
                    _OAuth2Editor(
                      tab: tab,
                      envVars: envVarsList,
                      resolvedEnvVars: resolvedVars,
                    ),
                  if (auth.type == AuthType.none)
                    Text('No authentication required.',
                        style: TextStyle(
                            color: context.colors.textSecondary, fontSize: 14)),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  String _authLabel(AuthType t) {
    switch (t) {
      case AuthType.none:
        return 'No Auth';
      case AuthType.bearer:
        return 'Bearer Token';
      case AuthType.basic:
        return 'Basic Auth';
      case AuthType.apiKey:
        return 'API Key';
      case AuthType.oauth2:
        return 'OAuth 2.0';
    }
  }
}

class _AuthField extends StatefulWidget {
  final String label;
  final String value;
  final String hint;
  final bool obscure;
  final ValueChanged<String> onChanged;
  final List<String>? envVars;
  final Map<String, String>? resolvedEnvVars;

  const _AuthField({
    required this.label,
    required this.value,
    required this.hint,
    required this.onChanged,
    this.obscure = false,
    this.envVars,
    this.resolvedEnvVars,
  });

  @override
  State<_AuthField> createState() => _AuthFieldState();
}

class _AuthFieldState extends State<_AuthField> {
  late VariableTextEditingController _ctrl;
  final FocusNode _focus = FocusNode();

  @override
  void initState() {
    super.initState();
    _ctrl = VariableTextEditingController(text: widget.value);
  }

  @override
  void dispose() {
    _ctrl.dispose();
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    _ctrl.variableColor = context.colors.warning;
    _ctrl.defaultColor = context.colors.textPrimary;

    final text = _ctrl.text;
    final hasVars = text.contains('{{');
    final resolvedText = (hasVars && widget.resolvedEnvVars != null)
        ? VariableParser.resolve(text, widget.resolvedEnvVars!)
        : null;

    Widget field = VariableAutocompleteField(
      controller: _ctrl,
      focusNode: _focus,
      obscureText: widget.obscure,
      envVars: widget.envVars ?? [],
      resolvedEnvVars: widget.resolvedEnvVars,
      onChanged: widget.onChanged,
      style: TextStyle(color: context.colors.textPrimary, fontSize: 14),
      decoration: InputDecoration(
        hintText: widget.hint,
        border: const OutlineInputBorder(),
      ),
    );

    if (resolvedText != null && resolvedText != text) {
      field = Tooltip(
        message: resolvedText,
        preferBelow: true,
        decoration: BoxDecoration(
          color: context.colors.bgElevated,
          borderRadius: BorderRadius.circular(6),
          border:
              Border.all(color: context.colors.warning.withValues(alpha: 0.4)),
        ),
        textStyle: TextStyle(
          fontSize: 12,
          color: context.colors.warning,
          fontFamily: 'monospace',
        ),
        child: field,
      );
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(widget.label,
            style: TextStyle(
                color: context.colors.textPrimary,
                fontWeight: FontWeight.bold,
                fontSize: 14)),
        const SizedBox(height: 8),
        field,
      ],
    );
  }
}

// ─── OAuth2 Editor ──────────────────────────────────────────────────────────

class _OAuth2Editor extends ConsumerStatefulWidget {
  final RequestTab tab;
  final List<String> envVars;
  final Map<String, String> resolvedEnvVars;

  const _OAuth2Editor({
    required this.tab,
    required this.envVars,
    required this.resolvedEnvVars,
  });

  @override
  ConsumerState<_OAuth2Editor> createState() => _OAuth2EditorState();
}

class _OAuth2EditorState extends ConsumerState<_OAuth2Editor> {
  late VariableTextEditingController _tokenUrlCtrl;
  late VariableTextEditingController _clientIdCtrl;
  late VariableTextEditingController _clientSecretCtrl;
  late VariableTextEditingController _authUrlCtrl;
  late VariableTextEditingController _redirectUrlCtrl;
  late VariableTextEditingController _usernameCtrl;
  late VariableTextEditingController _passwordCtrl;
  late VariableTextEditingController _scopeCtrl;

  @override
  void initState() {
    super.initState();
    final oauth2 = widget.tab.request.auth.oauth2Config;
    _tokenUrlCtrl = VariableTextEditingController(text: oauth2.tokenUrl);
    _clientIdCtrl = VariableTextEditingController(text: oauth2.clientId);
    _clientSecretCtrl =
        VariableTextEditingController(text: oauth2.clientSecret);
    _authUrlCtrl = VariableTextEditingController(text: oauth2.authorizationUrl);
    _redirectUrlCtrl = VariableTextEditingController(text: oauth2.redirectUrl);
    _usernameCtrl = VariableTextEditingController(text: oauth2.username);
    _passwordCtrl = VariableTextEditingController(text: oauth2.password);
    _scopeCtrl = VariableTextEditingController(text: oauth2.scope);
  }

  @override
  void didUpdateWidget(_OAuth2Editor old) {
    super.didUpdateWidget(old);
    if (old.tab.id != widget.tab.id) {
      final oauth2 = widget.tab.request.auth.oauth2Config;
      _tokenUrlCtrl.text = oauth2.tokenUrl;
      _clientIdCtrl.text = oauth2.clientId;
      _clientSecretCtrl.text = oauth2.clientSecret;
      _authUrlCtrl.text = oauth2.authorizationUrl;
      _redirectUrlCtrl.text = oauth2.redirectUrl;
      _usernameCtrl.text = oauth2.username;
      _passwordCtrl.text = oauth2.password;
      _scopeCtrl.text = oauth2.scope;
    }
  }

  @override
  void dispose() {
    _tokenUrlCtrl.dispose();
    _clientIdCtrl.dispose();
    _clientSecretCtrl.dispose();
    _authUrlCtrl.dispose();
    _redirectUrlCtrl.dispose();
    _usernameCtrl.dispose();
    _passwordCtrl.dispose();
    _scopeCtrl.dispose();
    super.dispose();
  }

  void _updateColors() {
    final colors = context.colors;
    for (final ctrl in [
      _tokenUrlCtrl,
      _clientIdCtrl,
      _clientSecretCtrl,
      _authUrlCtrl,
      _redirectUrlCtrl,
      _usernameCtrl,
      _passwordCtrl,
      _scopeCtrl
    ]) {
      ctrl.variableColor = colors.warning;
      ctrl.defaultColor = colors.textPrimary;
    }
  }

  String _flowLabel(OAuth2Flow flow) {
    switch (flow) {
      case OAuth2Flow.clientCredentials:
        return 'Client Credentials';
      case OAuth2Flow.authorizationCode:
        return 'Authorization Code';
      case OAuth2Flow.password:
        return 'Password';
      case OAuth2Flow.implicit:
        return 'Implicit';
    }
  }

  @override
  Widget build(BuildContext context) {
    _updateColors();
    final req = widget.tab.request;
    final auth = req.auth;
    final oauth2 = auth.oauth2Config;
    final notifier = ref.read(tabsProvider.notifier);

    return SingleChildScrollView(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Flow selector
          Text('Flow',
              style: TextStyle(
                  color: context.colors.textPrimary,
                  fontWeight: FontWeight.bold,
                  fontSize: 14)),
          const SizedBox(height: 8),
          DropdownButtonFormField<OAuth2Flow>(
            initialValue: oauth2.flow,
            dropdownColor: context.colors.bgElevated,
            style: TextStyle(color: context.colors.textPrimary, fontSize: 14),
            decoration: const InputDecoration(
              border: OutlineInputBorder(),
              isDense: true,
            ),
            items: OAuth2Flow.values.map((f) {
              return DropdownMenuItem(
                value: f,
                child: Text(_flowLabel(f)),
              );
            }).toList(),
            onChanged: (f) => f != null
                ? notifier.updateRequest(
                    widget.tab.id,
                    req.copyWith(
                      auth: auth.copyWith(
                        oauth2Config: oauth2.copyWith(flow: f),
                      ),
                    ),
                  )
                : null,
          ),
          const SizedBox(height: 16),

          // Token URL
          Text('Token URL',
              style: TextStyle(
                  color: context.colors.textPrimary,
                  fontWeight: FontWeight.bold,
                  fontSize: 14)),
          const SizedBox(height: 8),
          VariableAutocompleteField(
            style: TextStyle(color: context.colors.textPrimary, fontSize: 14),
            decoration: const InputDecoration(
              border: OutlineInputBorder(),
              hintText: 'https://oauth.example.com/token',
              isDense: true,
            ),
            controller: _tokenUrlCtrl,
            envVars: widget.envVars,
            resolvedEnvVars: widget.resolvedEnvVars,
            onChanged: (v) => notifier.updateRequest(
              widget.tab.id,
              req.copyWith(
                auth: auth.copyWith(
                  oauth2Config: oauth2.copyWith(tokenUrl: v),
                ),
              ),
            ),
          ),
          const SizedBox(height: 16),

          // Client ID
          Text('Client ID',
              style: TextStyle(
                  color: context.colors.textPrimary,
                  fontWeight: FontWeight.bold,
                  fontSize: 14)),
          const SizedBox(height: 8),
          VariableAutocompleteField(
            style: TextStyle(color: context.colors.textPrimary, fontSize: 14),
            decoration: const InputDecoration(
              border: OutlineInputBorder(),
              isDense: true,
            ),
            controller: _clientIdCtrl,
            envVars: widget.envVars,
            resolvedEnvVars: widget.resolvedEnvVars,
            onChanged: (v) => notifier.updateRequest(
              widget.tab.id,
              req.copyWith(
                auth: auth.copyWith(
                  oauth2Config: oauth2.copyWith(clientId: v),
                ),
              ),
            ),
          ),
          const SizedBox(height: 16),

          // Client Secret
          Text('Client Secret',
              style: TextStyle(
                  color: context.colors.textPrimary,
                  fontWeight: FontWeight.bold,
                  fontSize: 14)),
          const SizedBox(height: 8),
          VariableAutocompleteField(
            style: TextStyle(color: context.colors.textPrimary, fontSize: 14),
            decoration: const InputDecoration(
              border: OutlineInputBorder(),
              isDense: true,
            ),
            controller: _clientSecretCtrl,
            obscureText: true,
            envVars: widget.envVars,
            resolvedEnvVars: widget.resolvedEnvVars,
            onChanged: (v) => notifier.updateRequest(
              widget.tab.id,
              req.copyWith(
                auth: auth.copyWith(
                  oauth2Config: oauth2.copyWith(clientSecret: v),
                ),
              ),
            ),
          ),
          const SizedBox(height: 16),

          // Authorization URL (for Authorization Code flow)
          if (oauth2.flow == OAuth2Flow.authorizationCode) ...[
            Text('Authorization URL',
                style: TextStyle(
                    color: context.colors.textPrimary,
                    fontWeight: FontWeight.bold,
                    fontSize: 14)),
            const SizedBox(height: 8),
            VariableAutocompleteField(
              style: TextStyle(color: context.colors.textPrimary, fontSize: 14),
              decoration: const InputDecoration(
                border: OutlineInputBorder(),
                hintText: 'https://oauth.example.com/authorize',
                isDense: true,
              ),
              controller: _authUrlCtrl,
              envVars: widget.envVars,
              resolvedEnvVars: widget.resolvedEnvVars,
              onChanged: (v) => notifier.updateRequest(
                widget.tab.id,
                req.copyWith(
                  auth: auth.copyWith(
                    oauth2Config: oauth2.copyWith(authorizationUrl: v),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 16),
            Text('Redirect URL',
                style: TextStyle(
                    color: context.colors.textPrimary,
                    fontWeight: FontWeight.bold,
                    fontSize: 14)),
            const SizedBox(height: 8),
            VariableAutocompleteField(
              style: TextStyle(color: context.colors.textPrimary, fontSize: 14),
              decoration: const InputDecoration(
                border: OutlineInputBorder(),
                hintText: 'http://localhost:8080/callback',
                isDense: true,
              ),
              controller: _redirectUrlCtrl,
              envVars: widget.envVars,
              resolvedEnvVars: widget.resolvedEnvVars,
              onChanged: (v) => notifier.updateRequest(
                widget.tab.id,
                req.copyWith(
                  auth: auth.copyWith(
                    oauth2Config: oauth2.copyWith(redirectUrl: v),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 16),
          ],

          // Username & Password (for Password flow)
          if (oauth2.flow == OAuth2Flow.password) ...[
            Text('Username',
                style: TextStyle(
                    color: context.colors.textPrimary,
                    fontWeight: FontWeight.bold,
                    fontSize: 14)),
            const SizedBox(height: 8),
            VariableAutocompleteField(
              style: TextStyle(color: context.colors.textPrimary, fontSize: 14),
              decoration: const InputDecoration(
                border: OutlineInputBorder(),
                isDense: true,
              ),
              controller: _usernameCtrl,
              envVars: widget.envVars,
              resolvedEnvVars: widget.resolvedEnvVars,
              onChanged: (v) => notifier.updateRequest(
                widget.tab.id,
                req.copyWith(
                  auth: auth.copyWith(
                    oauth2Config: oauth2.copyWith(username: v),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 16),
            Text('Password',
                style: TextStyle(
                    color: context.colors.textPrimary,
                    fontWeight: FontWeight.bold,
                    fontSize: 14)),
            const SizedBox(height: 8),
            VariableAutocompleteField(
              style: TextStyle(color: context.colors.textPrimary, fontSize: 14),
              decoration: const InputDecoration(
                border: OutlineInputBorder(),
                isDense: true,
              ),
              controller: _passwordCtrl,
              obscureText: true,
              envVars: widget.envVars,
              resolvedEnvVars: widget.resolvedEnvVars,
              onChanged: (v) => notifier.updateRequest(
                widget.tab.id,
                req.copyWith(
                  auth: auth.copyWith(
                    oauth2Config: oauth2.copyWith(password: v),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 16),
          ],

          // Scope
          Text('Scope (optional)',
              style: TextStyle(
                  color: context.colors.textPrimary,
                  fontWeight: FontWeight.bold,
                  fontSize: 14)),
          const SizedBox(height: 8),
          VariableAutocompleteField(
            style: TextStyle(color: context.colors.textPrimary, fontSize: 14),
            decoration: const InputDecoration(
              border: OutlineInputBorder(),
              hintText: 'read write',
              isDense: true,
            ),
            controller: _scopeCtrl,
            envVars: widget.envVars,
            resolvedEnvVars: widget.resolvedEnvVars,
            onChanged: (v) => notifier.updateRequest(
              widget.tab.id,
              req.copyWith(
                auth: auth.copyWith(
                  oauth2Config: oauth2.copyWith(scope: v),
                ),
              ),
            ),
          ),
          const SizedBox(height: 16),

          // Fetch Token button
          ElevatedButton.icon(
            onPressed: () => _fetchToken(context, ref),
            icon: const Icon(Icons.refresh),
            label: const Text('Fetch Token'),
          ),
          const SizedBox(height: 16),

          // Token info
          if (oauth2.accessToken.isNotEmpty) ...[
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                border: Border.all(color: context.colors.textMuted),
                borderRadius: BorderRadius.circular(4),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('Access Token (masked)',
                      style: TextStyle(
                          color: context.colors.textMuted, fontSize: 11)),
                  const SizedBox(height: 4),
                  Text('••••••',
                      style: TextStyle(
                          color: context.colors.textSecondary, fontSize: 12)),
                  const SizedBox(height: 8),
                  if (oauth2.tokenExpiry != null)
                    Text(
                      'Expires: ${oauth2.tokenExpiry!.toLocal().toString().split('.')[0]}',
                      style: TextStyle(
                          color: context.colors.textSecondary, fontSize: 12),
                    ),
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }

  Future<void> _fetchToken(BuildContext context, WidgetRef ref) async {
    final req = widget.tab.request;
    final auth = req.auth;
    final oauth2 = auth.oauth2Config;
    final notifier = ref.read(tabsProvider.notifier);

    if (oauth2.tokenUrl.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Token URL is required')),
      );
      return;
    }

    try {
      final Map<String, dynamic> body = {
        'grant_type': _grantType(oauth2.flow),
        'client_id': oauth2.clientId,
      };

      if (oauth2.clientSecret.isNotEmpty) {
        body['client_secret'] = oauth2.clientSecret;
      }

      switch (oauth2.flow) {
        case OAuth2Flow.clientCredentials:
          body['grant_type'] = 'client_credentials';
          break;
        case OAuth2Flow.password:
          body['grant_type'] = 'password';
          body['username'] = oauth2.username;
          body['password'] = oauth2.password;
          break;
        case OAuth2Flow.authorizationCode:
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
                content: Text(
                    'Authorization Code flow requires browser interaction')),
          );
          return;
        case OAuth2Flow.implicit:
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Implicit flow not supported')),
          );
          return;
      }

      if (oauth2.scope.isNotEmpty) {
        body['scope'] = oauth2.scope;
      }

      final httpService = HttpService();
      final tokenResponse = await httpService.fetchOAuth2Token(
        oauth2.tokenUrl,
        body,
      );

      if (tokenResponse != null) {
        final accessToken = tokenResponse['access_token'] ?? '';
        final expiresIn = tokenResponse['expires_in'] ?? 0;
        final refreshToken = tokenResponse['refresh_token'] ?? '';

        final tokenExpiry = expiresIn > 0
            ? DateTime.now().add(Duration(seconds: expiresIn as int))
            : null;

        if (!mounted) return;

        notifier.updateRequest(
          widget.tab.id,
          req.copyWith(
            auth: auth.copyWith(
              oauth2Config: oauth2.copyWith(
                accessToken: accessToken,
                expiresIn: expiresIn,
                refreshToken: refreshToken,
                tokenExpiry: tokenExpiry,
              ),
            ),
          ),
        );

        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Token fetched successfully')),
        );
      } else {
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Failed to fetch token')),
        );
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error: $e')),
      );
    }
  }

  String _grantType(OAuth2Flow flow) {
    switch (flow) {
      case OAuth2Flow.clientCredentials:
        return 'client_credentials';
      case OAuth2Flow.password:
        return 'password';
      case OAuth2Flow.authorizationCode:
        return 'authorization_code';
      case OAuth2Flow.implicit:
        return 'implicit';
    }
  }
}

// ─── Auto-Generated Headers ─────────────────────────────────────────────────

class _AutoGeneratedHeaders extends StatelessWidget {
  final ApiRequest request;
  const _AutoGeneratedHeaders({required this.request});

  @override
  Widget build(BuildContext context) {
    final autoHeaders = HttpUtils.computeAutoHeaders(request);

    if (autoHeaders.isEmpty) {
      return const SizedBox.shrink();
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Padding(
          padding: const EdgeInsets.only(left: 16, top: 24, bottom: 8),
          child: Row(
            children: [
              Icon(Icons.auto_fix_high_outlined,
                  size: 12,
                  color: context.colors.accent.withValues(alpha: 0.7)),
              const SizedBox(width: 8),
              Text(
                'AUTO-GENERATED HEADERS',
                style: TextStyle(
                  fontSize: 10,
                  fontWeight: FontWeight.w700,
                  color: context.colors.accent.withValues(alpha: 0.7),
                  letterSpacing: 1.2,
                ),
              ),
            ],
          ),
        ),
        Container(
          margin: const EdgeInsets.symmetric(horizontal: 16),
          decoration: BoxDecoration(
            color: context.colors.bgSurface,
            borderRadius: BorderRadius.circular(6),
            border: Border.all(color: context.colors.border, width: 0.5),
          ),
          child: Column(
            children: autoHeaders.asMap().entries.map((itemEntry) {
              final i = itemEntry.key;
              final entry = itemEntry.value;
              final isLast = i == autoHeaders.length - 1;

              return Tooltip(
                message:
                    'This header is automatically computed by Mapia based on your request config (auth/body type).',
                waitDuration: const Duration(milliseconds: 500),
                child: Container(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                  decoration: BoxDecoration(
                    border: isLast
                        ? null
                        : Border(
                            bottom: BorderSide(
                                color: context.colors.border, width: 0.5)),
                  ),
                  child: Row(
                    children: [
                      Icon(Icons.lock_outline,
                          size: 12, color: context.colors.textMuted),
                      const SizedBox(width: 12),
                      SizedBox(
                        width: 160,
                        child: Text(
                          entry.key,
                          style: TextStyle(
                            fontSize: 12,
                            fontWeight: FontWeight.w500,
                            color: context.colors.textSecondary,
                            fontFamily: 'monospace',
                          ),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          entry.value,
                          style: TextStyle(
                            fontSize: 12,
                            color: context.colors.textMuted,
                            fontFamily: 'monospace',
                          ),
                          overflow: TextOverflow.ellipsis,
                        ),
                      ),
                    ],
                  ),
                ),
              );
            }).toList(),
          ),
        ),
        const SizedBox(height: 16),
      ],
    );
  }
}
